### PR TITLE
feat(i18n): RTL support

### PR DESCRIPTION
**Pull request by mmmoussa**
# Description

This library works great for left-to-right languages but is currently broken for right-to-left languages due to a bug with the positioning logic. I have fixed this bug and tested the fix in both ltr and rtl.

### Result

Before:
https://user-images.githubusercontent.com/9062287/116790374-c6ef3280-aa81-11eb-8317-88cb0111bcda.mov

After:
https://user-images.githubusercontent.com/9062287/116790478-57c60e00-aa82-11eb-8a69-958023f78ca8.mov

### CODE REVIEW

**Review by VincentCATILLON — APPROVED** [review]

**Comment by VincentCATILLON** [comment]
Hi @mmmoussa ,

Thanks a lot for your contribution, it's really appreciated and sorry about the delay used to review it

**Comment by mmmoussa** [comment]
Happy to contribute!

**Comment by MuhammedAlkhudiryZid** [comment]
@mmmoussa @VincentCATILLON, thank you for fixing this, is it released yet? because it does not seem to be released..

**Comment by cashbackdev** [comment]
> @mmmoussa @VincentCATILLON, thank you for fixing this, is it released yet? because it does not seem to be released..

Same... did you find a solution ?
NPM doesnt seem to be linked to the new version
maybe it should be changed to 1.5.3 ...?

**Comment by MuhammedAlkhudiryZid** [comment]
@cashbackdev use patch-package

**Pull request merged**
